-- Alerting Definition Sets
-- https://www.symantec.com/connect/articles/compilation-sql-queries-sepm-database#comment-12020701
-- Eddie Velez https://www.symantec.com/connect/user/eddie-velez
SELECT COMPUTER_NAME,
	IP_ADDR1_TEXT,
	CURRENT_LOGIN_USER,
	AV_DEF,
	IPS_DEF,
	SONAR_DEF,
	MRCLEAN_DEF,
	AGENT_VERSION,
	COMPUTER_DOMAIN_NAME,
	OPERATION_SYSTEM,
	STATUS,
	LAST_UPDATE_TIME,
	LAST_SCAN_TIME,
	FREE_MEM,
	FREE_DISK
FROM [sem5].[dbo].[AGENT_DEF_CACHE]
INNER JOIN SEM_AGENT ON SEM_AGENT.AGENT_ID = AGENT_DEF_CACHE.AGENT_ID
INNER JOIN V_SEM_COMPUTER ON V_SEM_COMPUTER.COMPUTER_ID = SEM_AGENT.COMPUTER_ID
WHERE V_SEM_COMPUTER.DELETED = 0
ORDER BY AV_DEF DESC