-- Hardware and BIOS check
-- https://www.symantec.com/connect/articles/compilation-sql-queries-sepm-database
-- SebastianZ
SELECT DISTINCT SC.COMPUTER_NAME,
	SC.IP_ADDR1_TEXT,
	MAC_ADDR1,
	G.NAME "Group Name",
	SC.BIOS_VERSION,
	OPERATION_SYSTEM,
	PROCESSOR_TYPE,
	PROCESSOR_NUM,
	MEMORY
FROM dbo.V_SEM_COMPUTER SC
INNER JOIN dbo.V_AGENT_SYSTEM_LOG ASL ON SC.COMPUTER_ID = ASL.COMPUTER_ID
INNER JOIN dbo.V_GROUPS G ON ASL.GROUP_ID = G.ID
WHERE G.NAME NOT LIKE '%YOUR_VIRTUAL_GROUP_FOR_CLIENTS%'
	AND G.NAME NOT LIKE '%YOUR_VIRTUAL_GROUP_FOR_SERVERS%'
	AND SC.BIOS_VERSION IN (
		SELECT BIOS_VERSION
		FROM dbo.V_SEM_COMPUTER
		WHERE BIOS_VERSION LIKE '%INTEL  - 6040000%'
			OR BIOS_VERSION LIKE '%XEN%'
			OR BIOS_VERSION LIKE '%VBOX%'
			OR BIOS_VERSION LIKE '%VRTUAL%'
		)
ORDER BY SC.COMPUTER_NAME;