-- SEP Client Information
-- https://www.symantec.com/connect/articles/compilation-sql-queries-sepm-database
-- SebastianZ
SELECT DISTINCT "SEM_CLIENT"."COMPUTER_NAME" "Computer Name",
	"SEM_AGENT"."AGENT_VERSION" "SEP Version",
	"SEM_COMPUTER"."OPERATION_SYSTEM" "Operation System",
	"PATTERN"."VERSION" "AV Revision",
	dateadd(s, convert(BIGINT, "SEM_AGENT"."CREATION_TIME") / 1000, '01-01-1970 00:00:00') CREATION_DTTM,
	dateadd(s, convert(BIGINT, "SEM_AGENT"."LAST_UPDATE_TIME") / 1000, '01-01-1970 00:00:00') "Last Update Time",
	dateadd(s, convert(BIGINT, LAST_SCAN_TIME) / 1000, '01-01-1970 00:00:00') "Last Scan Time",
	"SEM_CLIENT"."USER_NAME" "User Name",
	"IP_ADDR1_TEXT" "IP Address",
	"IDENTITY_MAP"."NAME" "Group Name",
	"SEM_AGENT"."DELETED" "Marked for deletion"
FROM (
	(
		(
			(
				"SEM_AGENT" "SEM_AGENT" INNER JOIN "SEM_CLIENT" "SEM_CLIENT" ON (
						("SEM_AGENT"."COMPUTER_ID" = "SEM_CLIENT"."COMPUTER_ID")
						AND ("SEM_AGENT"."DOMAIN_ID" = "SEM_CLIENT"."DOMAIN_ID")
						)
					AND ("SEM_AGENT"."GROUP_ID" = "SEM_CLIENT"."GROUP_ID")
				) INNER JOIN "SEM_COMPUTER" "SEM_COMPUTER" ON (
					("SEM_AGENT"."COMPUTER_ID" = "SEM_COMPUTER"."COMPUTER_ID")
					AND ("SEM_AGENT"."DOMAIN_ID" = "SEM_COMPUTER"."DOMAIN_ID")
					)
				AND ("SEM_AGENT"."DELETED" = "SEM_COMPUTER"."DELETED")
			) INNER JOIN "PATTERN" "PATTERN" ON "SEM_AGENT"."PATTERN_IDX" = "PATTERN"."PATTERN_IDX"
		) INNER JOIN "IDENTITY_MAP" "IDENTITY_MAP" ON "SEM_CLIENT"."GROUP_ID" = "IDENTITY_MAP"."ID"
	)
INNER JOIN "V_SEM_COMPUTER" "V_SEM_COMPUTER" ON "SEM_COMPUTER"."COMPUTER_ID" = "V_SEM_COMPUTER"."COMPUTER_ID"
	AND "SEM_AGENT"."DELETED" = 0
ORDER BY "Computer Name"