-- SEP to SEPM Server mapping
-- https://www.symantec.com/connect/articles/compilation-sql-queries-sepm-database
-- SebastianZ
SELECT SEM_CLIENT.COMPUTER_NAME AS Computer,
	SEM_AGENT.LAST_SERVER_ID AS SERVER,
	SEM_AGENT.STATUS AS STATUS,
	SEM_COMPUTER.IP_ADDR1 AS IP
FROM SEM_CLIENT,
	SEM_AGENT,
	SEM_COMPUTER
WHERE SEM_AGENT.COMPUTER_ID = SEM_CLIENT.COMPUTER_ID
	AND SEM_AGENT.STATUS = 1
	AND SEM_CLIENT.COMPUTER_NAME = SEM_COMPUTER.COMPUTER_NAME