-- Virus definitions query
-- https://www.symantec.com/connect/articles/compilation-sql-queries-sepm-database
-- SebastianZ
SELECT SEM_COMPUTER.COMPUTER_NAME AS 'Computer name',
	PATTERN.Version AS 'Virus definition used',
	dateadd(second, SEM_AGENT.LAST_UPDATE_TIME / 1000, '1970-01-01') AS 'Last check-in (GMT)',
	SEM_AGENT.AGENT_VERSION
FROM SEM_COMPUTER
INNER JOIN SEM_AGENT ON SEM_AGENT.COMPUTER_ID = SEM_COMPUTER.COMPUTER_ID
INNER JOIN SEM_CONTENT ON SEM_CONTENT.AGENT_ID = SEM_AGENT.AGENT_ID
INNER JOIN PATTERN ON PATTERN.PATTERN_IDX = SEM_AGENT.PATTERN_IDX
INNER JOIN (
	SELECT SEM_COMPUTER.COMPUTER_NAME AS 'TempHostName',
		MAX(SEM_AGENT.LAST_UPDATE_TIME) AS 'TempMax'
	FROM SEM_COMPUTER
	INNER JOIN SEM_AGENT ON SEM_AGENT.COMPUTER_ID = SEM_COMPUTER.COMPUTER_ID
	GROUP BY COMPUTER_NAME
	) TestTable ON TestTable.TempHostName = SEM_COMPUTER.COMPUTER_NAME
	AND TestTable.TempMax = SEM_AGENT.LAST_UPDATE_TIME
WHERE PATTERN.PATTERN_TYPE = 'VIRUS_DEFS'
	AND PATTERN.DELETED = '0'
	AND SEM_CONTENT.DELETED = '0'
	AND SEM_AGENT.DELETED = '0'
	AND SEM_COMPUTER.DELETED = '0'
GROUP BY SEM_COMPUTER.COMPUTER_NAME,
	SEM_AGENT.LAST_UPDATE_TIME,
	PATTERN.Version,
	SEM_AGENT.AGENT_VERSION
ORDER BY SEM_COMPUTER.COMPUTER_NAME ASC,
	SEM_AGENT.LAST_UPDATE_TIME DESC;